from django.db import models

# Create your models here.

class Articulos(models.Model):
    nombre= models.CharField(max_length=30)
    seccion= models.CharField(max_length=50)
    precio= models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.nombre
 
class IngenieriaGSM(models.Model):
    Sector=models.CharField(max_length=15)
    Btsname=models.CharField(max_length=15)
    Cellname=models.CharField(max_length=15)
    CellID=models.CharField(max_length=15)
    Latitud=models.FloatField()
    Longitud=models.FloatField()
    SiteName=models.CharField(max_length=80)
    FrequencyBand=models.IntegerField()
    TRXs=models.IntegerField()
    AntennaType=models.CharField(max_length=15)
    AntennaHeight=models.IntegerField()
    Azimuth=models.IntegerField()
    MechDownTilt=models.IntegerField()
    ElecDownTilt=models.IntegerField()
    SiteType=models.CharField(max_length=30)
    BSCID=models.CharField(max_length=20)
    MCC=models.IntegerField()
    MNC=models.IntegerField()
    LAC=models.IntegerField()
    RAC=models.IntegerField()
    BCCHFD=models.IntegerField()
    TCH=models.IntegerField()
    BSICbaseoctal=models.IntegerField()#charfield
    NCC=models.IntegerField()
    BCC=models.IntegerField()
    HSN=models.IntegerField()
    MAIO=models.CharField(max_length=10)
    PowerW=models.IntegerField()
    PowerdBm=models.DecimalField(decimal_places=1, max_digits=3)
    Departamento=models.CharField(max_length=50)
    Municipio=models.CharField(max_length=50)
    Area=models.CharField(max_length=40)
    Encargado=models.CharField(max_length=70)
    Telefono=models.CharField(max_length=20)
    RET=models.CharField(max_length=8)
    Ganancia=models.DecimalField(decimal_places=1, max_digits=4)
    Apertura=models.IntegerField()
    #def __str__(self):
    #    return self.Cellname

class IngenieriaUMTS(models.Model):
    NodeBName=models.CharField(max_length=20)
    Cellname=models.CharField(max_length=20)
    Latitud=models.FloatField()
    Longitud=models.FloatField()
    SiteCommonName=models.CharField(max_length=80)
    SiteName=models.CharField(max_length=80)
    RNC=models.CharField(max_length=20)
    RNCID= models.IntegerField()
    CELLID= models.IntegerField()
    LAC= models.IntegerField()
    RAC= models.IntegerField()
    SAC= models.IntegerField()
    URAID= models.IntegerField()
    UARFCNUPLINK= models.IntegerField()
    UARFCNDOWNLINK= models.IntegerField()
    PSC= models.IntegerField()
    CPICHPOWER= models.DecimalField(decimal_places=1, max_digits=3)
    AntennaType=models.CharField(max_length=40)
    AntennaHeight=models.IntegerField()
    Azimuth=models.IntegerField()
    MechDownTilt=models.IntegerField()
    ElecDownTilt=models.IntegerField()
    SiteType=models.CharField(max_length=40)
    RET=models.CharField(max_length=10)
    IPCKL=models.CharField(max_length=40)
    Departamento=models.CharField(max_length=40)
    Municipio=models.CharField(max_length=40)
    Area=models.CharField(max_length=40)
    Encargado=models.CharField(max_length=70)
    Telefono=models.CharField(max_length=20)
    Ganancia= models.DecimalField(decimal_places=1, max_digits=4)
    Apertura= models.IntegerField()

class IngenieriaLTE(models.Model):
    EnodeBName=models.CharField(max_length=30)
    CellIndex=models.CharField(max_length=30)
    Cell= models.CharField(max_length=30)
    Nombre=models.CharField(max_length=80)
    Latitud=models.FloatField()
    Longitud=models.FloatField()
    Departamento=models.CharField(max_length=60)
    Municipio=models.CharField(max_length=60)
    Area=models.CharField(max_length=60)
    Encargado=models.CharField(max_length=60)
    Telefono=models.CharField(max_length=20)
    Azimuth=models.IntegerField()
    AntennaHeight=models.IntegerField()
    MechDownTilt=models.IntegerField()
    ElecDownTilt=models.IntegerField()
    PCI= models.IntegerField()
    MinRootSequency= models.IntegerField()
    TAC= models.IntegerField()
    TAL= models.IntegerField()
    EARFCN_DL= models.IntegerField()
    EARFCN_UL= models.IntegerField()
    RSpower= models.DecimalField(decimal_places=1, max_digits=3)
    AntennaType= models.CharField(max_length=20)
    RET= models.CharField(max_length=10)
    Estructura= models.CharField(max_length=20)
    Ganancia= models.DecimalField(decimal_places=1, max_digits=4)
    Apertura= models.IntegerField()
