# Generated by Django 3.0.4 on 2020-03-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenierias', '0002_auto_20200309_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingenierialte',
            name='AntennaHeight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
