# Generated by Django 3.0.4 on 2020-03-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenierias', '0003_ingenierialte_antennaheight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingenierialte',
            name='Ganancia',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
