# Generated by Django 3.0.4 on 2020-03-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenierias', '0007_auto_20200316_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingenieriaumts',
            name='AntennaType',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ingenieriaumts',
            name='SiteType',
            field=models.CharField(max_length=40),
        ),
    ]
